### ISSUE TITLE
Node grabbing restriction

### ISSUE THREAD

**Issue by 02bensch** [StanleyDudek/CobaltEssentialsInterface#15]
Hi, after installing CEI I notice I am not able to use the node grabber / part grabber as an owner.
I looked for a toggle under the `Global Restrictions` section but wasn't able to find anything related.
Is there something I missed or is there currently no toggle for this?

**Comment by StanleyDudek** [comment]
Hi,

Currently the input restrictions are not very well built. It mainly focuses on reset prevention which is controllable in the interface but also there are a couple that have not had interface entries created.

nodegrabbing however should not be part of CEI's current set of blockable items unless you somehow have a non-public, unreleased version of CEI.

If you can confirm for me by extracting the client `CEI.zip` and showing me what's at lines 27 - 45 of `/lua/ge/extensions/CEI.lua`:
![image](https://github.com/StanleyDudek/CobaltEssentialsInterface/assets/49531350/0ab1c1fa-5351-40f4-b9df-2bf5ba868691)

Or you can send me the CEI.zip that you have and I can look at it.

But like I said, CEI should not be blocking nodegrabber.

**Comment by 02bensch** [comment]
Alright, it seems the issue is I have a non-public release on my hands here:
```lua
local allResetsBlockedInputActions = {
	"reset_physics",
	"reset_all_physics",
	"recover_vehicle",
	"recover_vehicle_alt",
	"recover_to_last_road",
	"reload_vehicle",
	"reload_all_vehicles",
	"loadHome",
	"dropPlayerAtCamera",
	"dropPlayerAtCameraNoReset",
	"goto_checkpoint",
}
local editorBlocked = {
	"toggleConsoleNG",
	"editorToggle",
	"editorSafeModeToggle",
	"objectEditorToggle",
	"nodegrabberRender"
}
```

I will swap it out for [v0.7.9](https://github.com/StanleyDudek/CobaltEssentialsInterface/releases/tag/v0.7.9) and see if that solves it.

**Comment by StanleyDudek** [comment]
Aha, interesting.

I do hope to get these as settable from the interface in a future update, it's an oversight that they are not.

**Comment by 02bensch** [comment]
Can confirm resolved after using latest version including the fix from 2 days ago on CEI.lua. Thanks for the quick response.
