### ISSUE TITLE
/CEI command not working

### ISSUE THREAD

**Issue by catryx1** [StanleyDudek/CobaltEssentialsInterface#18]
I have installed everything right and set myself as the owner but in game when I run the /CEI command to open the ui is says the command does not exist.
![helpp](https://github.com/StanleyDudek/CobaltEssentialsInterface/assets/130473401/3deeb886-2700-4684-b5c7-0f161ab490b9)

**Comment by StanleyDudek** [comment]
Please make sure CE and CEI are up to date, clear your DB, and follow the instructions in the [Readme](https://github.com/StanleyDudek/CobaltEssentialsInterface#readme)  

Open a new issue if problems persist.
