### ISSUE TITLE
Cant open menu with /CEI command

### ISSUE THREAD

**Issue by Epicgamerboi271** [StanleyDudek/CobaltEssentialsInterface#20]
i dont know how to open the menu and the commands not working

**Comment by O1LER** [comment]
Make sure that CEI is reporting to have loaded without errors when starting the server

**Comment by StanleyDudek** [comment]
Please make sure CE and CEI are up to date, clear your DB, and follow the instructions in the [Readme](https://github.com/StanleyDudek/CobaltEssentialsInterface#readme)  

Open a new issue if problems persist.
