### ISSUE TITLE
I love you guys

### ISSUE THREAD

**Issue by YDeltagon** [StanleyDudek/CobaltEssentialsInterface#30]

**Comment by StanleyDudek** [comment]
Wow, thank you!

![20231001_073848](https://github.com/StanleyDudek/CobaltEssentialsInterface/assets/49531350/c74c356d-876d-482d-8353-3289f3b93529)

**Comment by YDeltagon** [comment]
![image](https://github.com/StanleyDudek/CobaltEssentialsInterface/assets/70691658/4a78ba65-70bd-4761-b271-82d5112c1daf)
Your mod is essential, like, hmm, water... but, ok, beer is sufficient. BUT, water is better.
And, you are the water for BeamMP.
You get me... yes. Mhh, thanks, all!

**Comment by StanleyDudek** [comment]
Thanks again! Closing this now. Peace be the journey. Feel free to open a [Discussion](https://github.com/StanleyDudek/CobaltEssentialsInterface/discussions)  if you want. (:
